language: node_js
os:
  - linux
  - osx
node_js:
  - '6'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - npm run test


matrix:
  allow_failures:
    - os: osx # OS X is still beta in Travis
